"""Regenerate every showcase artifact from data/fhrcc_pathway_v1.json.

    python scripts/build_showcase.py

Writes static figures to docs/figures/, the interactive explorer to docs/index.html
(served by GitHub Pages), and a plain-text audit to reports/graph_audit.md.
Figures need the optional extra:  pip install -e ".[viz]"
"""
from __future__ import annotations
import argparse
from pathlib import Path
from fhrcc_mechanismkg.analysis import (
    edges_into,
    evidence_counts,
    is_hypothesis,
    path_summary,
    reachable,
)
from fhrcc_mechanismkg.io import graph_from_json
from fhrcc_mechanismkg.reasoning.path_search import k_shortest_paths_explainable

SOURCE, TARGET = "gene:FH", "phenotype:cancer"


def write_audit(graph, paths, out: Path) -> None:
    best = paths[0]
    s = path_summary(best)
    counts = evidence_counts(graph)
    into = edges_into(graph, TARGET)
    lines = [
        "# Graph audit (auto-generated by scripts/build_showcase.py)",
        "",
        f"- Nodes: {len(graph.nodes)}; edges: {len(graph.edges)}",
        f"- Hypothesis-level edges: {counts['hypothesis']} of {len(graph.edges)} ({counts['hypothesis'] / len(graph.edges):.0%})",
        "- Evidence levels with zero edges: " + (", ".join(k for k, v in counts.items() if v == 0) or "none"),
        f"- Edges into {TARGET}: {len(into)}; hypothesis-level: {sum(is_hypothesis(e) for e in into)}",
        f"- {SOURCE} -> {TARGET} reachable using supported edges only: {reachable(graph, SOURCE, TARGET, include_hypothesis = False)}",
        f"- Best path: cost {s['cost']:.3f}, {int(s['hops'])} hops, {int(s['n_hypothesis_edges'])} hypothesis edge(s)",
        f"- Weakest edge on best path carries {s['weakest_edge_share']:.0%} of its total cost",
        "",
        "## Top paths",
    ]
    for i, p in enumerate(paths, 1):
        ps = path_summary(p)
        via = " -> ".join(graph.nodes[n].name for n in p.node_ids())
        lines.append(f"{i}. cost {ps['cost']:.3f}, {int(ps['hops'])} hops, {int(ps['n_hypothesis_edges'])} hypothesis edges: {via}")
    out.parent.mkdir(parents = True, exist_ok = True)
    out.write_text("\n".join(lines) + "\n", encoding = "utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--graph", default = "data/fhrcc_pathway_v1.json")
    ap.add_argument("--k", type = int, default = 8)
    ap.add_argument("--skip-figures", action = "store_true", help = "Only build the HTML explorer and audit")
    args = ap.parse_args()

    g = graph_from_json(args.graph)
    paths = k_shortest_paths_explainable(g, SOURCE, TARGET, k = args.k, max_hops = 14)
    best = paths[0]
    n_hyp = evidence_counts(g)["hypothesis"]
    src_name, tgt_name = g.nodes[SOURCE].name, g.nodes[TARGET].name
    into = edges_into(g, TARGET)

    write_audit(g, paths, Path("reports/graph_audit.md"))

    if not args.skip_figures:
        from fhrcc_mechanismkg import viz

        viz.draw_overview(
            g,
            "docs/figures/graph_overview.png",
            highlight = best,
            title = "FH-deficient RCC mechanism knowledge graph",
            subtitle = f"{len(g.nodes)} entities, {len(g.edges)} causal claims. {n_hyp} claims are hypothesis-level, including all {len(into)} edges into '{tgt_name}'.",
        )
        viz.draw_path_comparison(g, paths, "docs/figures/path_comparison.png", src_name, tgt_name)
        viz.draw_evidence_audit(g, best, "docs/figures/evidence_audit.png", src_name, tgt_name)

    from fhrcc_mechanismkg import web

    web.write_explorer(g, "docs/index.html", source = SOURCE)
    print("Wrote docs/figures/*.png, docs/index.html, reports/graph_audit.md")


if __name__ == "__main__":
    main()
